name: frontend

serviceType: NodePort

ports:
  - port: 5000
    targetPort: 5000
    nodePort: 32000

replicas: 1

container:
  command: /go/bin/frontend
  image: htliang/hotelreservation-new-rate
  name: hotel-reserv-frontend
  ports:
  - containerPort: 5000

  resources: |
    limits:
      cpu: 400m
      memory: 128Mi
    requests:
      cpu: 400m
      memory: 128Mi

configMaps:
  - name: service-config.json
    mountPath: config.json
    value: service-config


affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: type
          operator: NotIn
          values:
          - stateful