name: rate

replicas: 1

ports:
  - port: 8084
    targetPort: 8084
 
container:
  command: /go/bin/rate
  image: htliang/hotelreservation-remove-consul
  name: hotel-reserv-rate
  ports:
  - containerPort: 8084

  resources: |
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 1000m
      memory: 1024Mi
      
configMaps:
  - name: service-config.json
    mountPath: config.json
    value: service-config


affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: type
          operator: NotIn
          values:
          - stateful
