name: search

replicas: 1

ports:
  - port: 8082
    targetPort: 8082
    
container:
  command: /go/bin/search
  image: htliang/hotelreservation-new-rate
  name: hotel-reserv-search
  ports:
  - containerPort: 8082

  resources: |
    limits:
      cpu: 400m
      memory: 128Mi
    requests:
      cpu: 400m
      memory: 128Mi

configMaps:
  - name: service-config.json
    mountPath: config.json
    value: service-config

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: type
          operator: NotIn
          values:
          - stateful
