name: user

replicas: 1

ports:
  - port: 8086
    targetPort: 8086
 
container:
  command: /go/bin/user
  image: htliang/hotelreservation-remove-consul
  name: hotel-reserv-user
  ports:
  - containerPort: 8086

  resources: |
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 1000m
      memory: 1024Mi

configMaps:
  - name: service-config.json
    mountPath: config.json
    value: service-config


affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: type
          operator: NotIn
          values:
          - stateful